include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'


# LLVM with assertions

# TODO: upgrade to 1.4.1 once it has LLVM+asserts artifacts
asserts:1.4:
  extends:
    - .julia:source
    - .test
  variables:
    CI_CLONE_ARGS: '-b v1.4.0'
    CI_BUILD_ARGS: 'BINARYBUILDER_LLVM_ASSERTS=1'
    CI_ASSERTS: 'true'

# TODO: add 1.5.0 once it has LLVM+asserts artifacts


# CUDAnative.jl

.test_cudanative:
  extends: .test
  variables:
    NVIDIA_VISIBLE_DEVICES: 'all'
    NVIDIA_DRIVER_CAPABILITIES: 'all'
  script:
    - julia -e 'using Pkg;
                Pkg.develop(PackageSpec(path=pwd()));
                Pkg.build();'
    - julia -e 'using Pkg;
                Pkg.add(PackageSpec(name="CUDAnative", rev="master"));
                Pkg.test("CUDAnative");'

cudanative:1.4:
  extends:
    - .julia:1.4
    - .test_cudanative
  tags:
    - nvidia


# AMDGPUnative.jl

.test_amdgpunative:
  extends: .test
  image: rocm/dev-ubuntu-18.04
  script:
    - julia -e 'using Pkg;
                Pkg.develop(PackageSpec(path=pwd()));
                Pkg.build();'
    - julia -e 'using Pkg;
                Pkg.add(PackageSpec(name="AMDGPUnative", rev="jps/gpucompiler"));
                Pkg.test("AMDGPUnative");'

amdgpunative:1.4:
  extends:
    - .julia:1.4
    - .test_amdgpunative
  tags:
    - rocm
  allow_failure: true


# other tasks

coverage:
  extends:
    - .julia:1.4
    - .coverage
