include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'


# CUDAnative.jl

.test_cudanative:
  extends: .test
  image: ubuntu:bionic
  variables:
    NVIDIA_VISIBLE_DEVICES: 'all'
    NVIDIA_DRIVER_CAPABILITIES: 'all'
  script:
    - julia -e 'using Pkg;
                Pkg.develop(PackageSpec(path=pwd()));
                Pkg.build();'
    - julia -e 'using Pkg;
                Pkg.add(PackageSpec(name="CUDAnative", rev="tb/gpucompiler"));
                Pkg.test("CUDAnative");'

cudanative:1.3:
  extends:
    - .julia:1.3
    - .test_cudanative
  tags:
    - nvidia

cudanative:1.4:
  extends:
    - .julia:1.4
    - .test_cudanative
  tags:
    - nvidia
