language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.3
  - 1.4
  - nightly

jobs:
  allow_failures:
  - os: osx
    julia: nightly

notifications:
  email: false

codecov: true

branches:
  only:
    - master
