language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.3
  - 1.4
  - nightly

cache:
    directories:
     - /home/travis/.julia/

notifications:
  email: false

codecov: true

branches:
  only:
    - master
