language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.5
  - nightly

jobs:
  allow_failures:
  - julia: nightly

notifications:
  email: false

codecov: true

branches:
  only:
    - master
